schema: shared/graphql/schema/src/commonMain/graphql/schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://api.github.com/graphql
      headers:
        Authorization: bearer ${GITHUB_TOKEN}
      introspect: false
