name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: gradle

    - name: Insert GITHUB_TOKEN to local.properties
      run: echo "GITHUB_TOKEN={{ secrets.GITHUB_TOKEN }}" >> local.properties

    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.8.1
      with:
        arguments: bundle
